"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/env";
import { validatePlan } from "@/lib/planner/validate";
import { parseTime } from "@/lib/planner/time";
import {
  minutesToHHMM,
  slugify,
  toInstant,
  uniqueSlug,
} from "@/lib/planner/publish";
import { safeZone } from "@/lib/events/format";
import { generateCheckinToken } from "@/lib/checkin/qr";
import type { Plan } from "@/lib/planner/types";

export type PublishResult = { error?: string };

export type PublishPayload = {
  plan: Plan;
  date: string;
  start: string;
  end: string;
  /** minutes from getTimezoneOffset() on the client */
  tzOffset: number;
  /**
   * IANA zone name from the organizer's browser, e.g. "America/Los_Angeles".
   * Stored so the public page can render the event's own wall-clock times
   * rather than the reader's.
   */
  tzName?: string;
  /** Friendly event description generated by Claude and edited by the organizer. */
  eventDescription?: string;
  /** Optional event location. */
  location?: string;
};

/**
 * Writes the plan to Postgres: one event, its roles, its shifts.
 *
 * Validation runs again here. The editor already checks it and disables the
 * button, but a server action is a public endpoint — anything that arrives has
 * to be treated as unvalidated input.
 */
export async function publishEventAction(payload: PublishPayload): Promise<PublishResult> {
  if (!isSupabaseConfigured) {
    return {
      error:
        "Supabase isn't configured, so there's nowhere to save this yet. Add your project URL and anon key to .env.local, apply the migration, and restart.",
    };
  }

  const { plan, date, start, end, tzOffset, eventDescription, location } = payload;
  const timezone = safeZone(payload.tzName);

  const windowStart = parseTime(start);
  const windowEnd = parseTime(end);

  const issues = validatePlan(plan, { start: windowStart, end: windowEnd });
  const blocking = issues.filter((issue) => issue.level === "error");
  if (blocking.length > 0) {
    return { error: blocking[0].message };
  }

  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return { error: "Pick a date for the event." };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Your session expired. Log in again to publish." };
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .maybeSingle();

  if (profile?.role === "volunteer") {
    return {
      error:
        "Your account is set up as a volunteer. Switch to organizer on your dashboard to publish events.",
    };
  }

  // Unique slug: one query for the slugs that start the same way, then pick a
  // free suffix locally.
  const base = slugify(plan.title);
  const { data: clashes } = await supabase
    .from("events")
    .select("slug")
    .like("slug", `${base}%`);
  // "new" is reserved: /events/new is the planner, and a static route wins over
  // a dynamic one, so an event slugged "new" would have no reachable page.
  const slug = uniqueSlug(base, [
    "new",
    ...(clashes ?? []).map((row) => row.slug),
  ]);

  const descriptionText =
    eventDescription?.trim() ||
    plan.roles.map((role) => role.name).join(" · ");

  const { data: event, error: eventError } = await supabase
    .from("events")
    .insert({
      organizer_id: user.id,
      title: plan.title.trim(),
      description: descriptionText,
      location: location?.trim() || null,
      starts_at: toInstant(date, minutesToHHMM(windowStart), tzOffset),
      ends_at: toInstant(date, minutesToHHMM(windowEnd), tzOffset),
      slug,
      published: true,
      timezone,
      checkin_token: generateCheckinToken(),
    })
    .select("id, slug")
    .single();

  if (eventError || !event) {
    return { error: eventError?.message ?? "Couldn't create the event." };
  }

  // Roles first — shifts reference them.
  const { data: roles, error: rolesError } = await supabase
    .from("roles")
    .insert(
      plan.roles.map((role, index) => ({
        event_id: event.id,
        name: role.name.trim(),
        description: role.description.trim() || null,
        capacity: role.shifts.reduce((sum, shift) => sum + shift.headcount, 0),
        // Keep the planner's order — created_at can't (one statement, one
        // timestamp), and sorting alphabetically would scramble Setup →
        // working roles → Teardown.
        position: index,
      })),
    )
    .select("id, name");

  if (rolesError || !roles) {
    // Roll the event back so a half-saved plan isn't left behind.
    await supabase.from("events").delete().eq("id", event.id);
    return { error: rolesError?.message ?? "Couldn't save the roles." };
  }

  const idByName = new Map(roles.map((role) => [role.name.toLowerCase(), role.id]));

  const { error: shiftsError } = await supabase.from("shifts").insert(
    plan.roles.flatMap((role) => {
      const roleId = idByName.get(role.name.trim().toLowerCase());
      if (!roleId) return [];
      return role.shifts.map((shift) => ({
        role_id: roleId,
        starts_at: toInstant(date, shift.start, tzOffset),
        ends_at: toInstant(date, shift.end, tzOffset),
        capacity: shift.headcount,
      }));
    }),
  );

  if (shiftsError) {
    await supabase.from("events").delete().eq("id", event.id);
    return { error: shiftsError.message };
  }

  revalidatePath("/dashboard");
  redirect(`/dashboard?published=${encodeURIComponent(event.slug)}`);
}
